### ISSUE TITLE
Kandy.call.createVoipCall -  JSON error

### ISSUE THREAD

**Issue by srbaskar** [Kandy-IO/kandy-phonegap#11]
Now kandy Phonegap plugin is install successfully.

We are facing issue in call function.

OnDevice Ready call " Kandy.initialize();"

Then on call button i am calling this function i.e

Kandy.call.createVoipCall(function () { 
console.log("success call"); 
}, function (error) { 
console.log(error); 
console.log("fail call"); 
}, "user4@giftsoninternet.com", false);

error callback function is calling and receiving error in console.log i.e 
JSON error & fail call

I am not getting why this JSON error is showing all parameters are correct.

Please check and let me know what is issue and how i can fix it.

- Ajay Kumar

**Comment by khoadp** [comment]
Ajay, what device did you use to test? ARM or x86? Our plugin only runs on ARM. Just install CPU-Z to check your device is ARM or x86.

**Comment by khoadp** [comment]
I believe this issue has been fixed as we fixed:
https://github.com/Kandy-IO/kandy-phonegap/issues/9

Can you please try again?

**Comment by Ajay1412** [comment]
ok khapdp, we will check and get back to you after one hour.

**Comment by Ajay1412** [comment]
Yes issue is fixed, During call showing the default interface, Is it possible we can change it?

**Comment by khoadp** [comment]
Currently you can change css to style it. In case you want to change html/layout of it, we haven't supported it.

What exactly you want to change the interface? Can you do some screenshot/drawing so that we can get some sense of what you wanted so that we will see if we can support that.

**Comment by Ajay1412** [comment]
I have integrated you plugin in My Mobile App.  

Calling is not working Properly. There is gap in receiving voice. My WiFi Downloading Speed is 5 Mbps and Uploading Speed is 0.50 Mbps.
So it should be work. Please check it and let me know what is the issue.

**Comment by khoadp** [comment]
Hi Ajay,

Did you mean call is working fine, the problem is just about some delay when receiving call? Can you try the demo app (demo/www) and see if there is the same issue? I don't have your codes so don't know how to reproduce it. If you suspect something in the logs, you can send it over and I'll look at it.

I don't know if we can do as WhatsApp. I need to do some research on it.

**Comment by Ajay1412** [comment]
Hi Khoadp,

Please provide me your skype id, So we can discuss on skype.

We have checked with your demo code. Same issue is occurring during voice call.
i.e if A is calling to B, Voice of A is listening clear to B for little bit time then stop listening voice on B end for 5 sec approx then again voice listening start. This process is happening again and again in voice converstation. Same case for B to A calling. 

Network Speed Downloading is 2 Mbps & Uploading 5 Mbps.
So it should be work properly. Above issue is in case of Mobile to Mobile communication with Wifi Network.We have also tried it with Mobile to WebView Calling and that case voice calling is ok no any voice breakage during voice conversation.

I am going to share You Demo Source code by which i have created the Phonegap application i.e 
https://www.dropbox.com/s/sodh7h443wpcerk/KandyDemo.zip?dl=0

Android APK Link i.e https://www.dropbox.com/s/z30q0aemfejjoe0/MainActivity-debug.apk?dl=0

Please check the source code if any issue then let me know. Also let me know your availability time so we can discuss on Skype.

**Comment by khoadp** [comment]
Hi Ajay,

Can you download a pure Kandy Android app and test on 2 mobiles?

https://rink.hockeyapp.net/api/2/apps/9846845b4e90da8b044c60b17aa394d1/app_versions/25?format=apk&avtoken=e60376bcb614ea51eb49c842fe219e98b6abecb5

That way we want to confirm if it's related to phonegap or pure Android SDK.

My skype is: dkhoa81

**Comment by Ajay1412** [comment]
My Skype Id is tap_php06  .I have Sent you skype request please add me

**Comment by khoadp** [comment]
From Ajay: the same behavior when using StarterApp

**Comment by khoadp** [comment]
Answer from Android team:

"Hopefully the Product updgare planned for end of this week will improve this"

Ajay, I'll update you when we're done the upgrade on our end.
