### ISSUE TITLE
message object sender set incorrectly

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#15]
For ex - If User1 (user1@anup.com) sends a chat message to User2 (user2@anup.com)

For User2 - The Kandy.onChatReceived message payload looks like 

     {
        "UUID":"46242C4A-D47A-4098-8DE1-19A5482D1F0F",
        "messageType":"chat",
        "timestamp":1419979765811,
         "sender": "user2@anup.com", // ??? This should be user1@anup.com
        "contentType":"text",
        "message":{
            "mimeType":"text/plain",
            "text":"hello world"
        }
    },

This is also reproducible in the demo app.

**Comment by primableatom** [comment]
When can I expect this issue to be fixed? The problem is message obj sender is set incorrectly to recipient !!! 

I am working on a file sharing feature and can't get the name of the sender (who sent me this file?)

For the text message I was able to get around this by putting the sender in the message text and the parsing that BUT for file sharing its a blocker

**Comment by khoadp** [comment]
Feedback from Android team:
"I cant reproduce this issue. For me its work ok and the sender is correct.
Maybe its related to the problem we saw between old and new SDK. 
Please ask him to do this test between two Android clients with the latest SDK"

Anup, where did you see that sender issue? Between 2 mobiles or between mobile and web?
Can you try the StarterApp that I sent you another day?

**Comment by primableatom** [comment]
The issue happened with mobile to mobile for me. I am using the latest master of the plugin and this issue is reproducible even in the demo example app too.

BTW I can't see any latest commits with Android SDK update, so I assume I am using the latest one unless I need to update it manually from somewhere
