### ISSUE TITLE
Need to set APIKey and SecretKey in File of Plugin

### ISSUE THREAD

**Issue by Ajay1412** [Kandy-IO/kandy-phonegap#21]
No need to install plugin by passing  APIKey and SecretKey in command line i.e 

cordova plugin add C:\Users\intersoft-admin\Downloads\kandy-phonegap-master --variable API_KEY=DAKf52569b2850c49929ee36c9861787e69 --variable API_SECRET=DASe213236317e44b72b53a1a8c25d8242e

Because after installing the plugin if i remove the platform and add platform again then error message is showing to pass the API_KEY and API_SECRET.
We have removed plugin and then add platform and then again fire install plugin command.

I just want to API_KEY and API_SECRET in any config file. By which i can remove and add platform without removing plugin again. Like other plugin installation work.

**Comment by primableatom** [comment]
Its already there, undocumented I guess.. as I asked for this feature ad hoc.. 

Kandy.setKey(null, null, key, secret) // first two nulls are for success and error callbacks, they are not really important as there is nothing async here.

**Comment by khoadp** [comment]
This is done.
