### ISSUE TITLE
Phonegap android settings not update the api & secret keys

### ISSUE THREAD

**Issue by memunis** [Kandy-IO/kandy-phonegap#26]
In android phonegap settings, We are unable to update the project api key & secret key. It always reverts back to default keys i.e api & secret keys provided in app when it was build.

Whenever we provision a new user, it always gets added to the default domain i.e @jupiter.kodeplus.net.

How do we get the domain api & secret keys updated in the app.

**Comment by khoadp** [comment]
This is fixed. Please try again. Thanks!
