### ISSUE TITLE
Missing contentType from chat details while calling Kandy.chat.sendChat

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#3]
I did a Kandy.chat.sendChat from the mobile app:
Kandy.chat.sendChat(
                        function(){
                            alert('message sent success');
                        },
                        function(e){
                            alert(e);
                        },
                        'user1@anup.com',
                        'customer needs help'
                    );
 
In the web app upon doing KandyAPI.phone.getIm:

KandyAPI.Phone.getIm(function(data){
   var message = data.messages[0];
   console.log(message.contentType); // this is undefined
   console.log(message);
   // all the other details are their EXCEPT contentType
   /**
    Object {UUID: "9FF4294E-2E41-45D2-98C9-77D1E147742C", messageType: "chat", timestamp: 1429528904233, sender: Object, message: Object}
    UUID: "9FF4294E-2E41-45D2-98C9-77D1E147742C"
    message: Object
    messageType: "chat"
    sender: Object
    timestamp: 1429528904233
  **/    
})

**Comment by khoadp** [comment]
I can confirm the message object sent from mobile is missing contentType="text". There is a check in chat.html, line 130 that stop the web receive chat message.

Starter App has the same issue. This is the core issue of Android SDK 1.4.17.

Srini, please inform Kandy Android SDK team on the issue. I'm not sure who I should assign the issue to so please take the ownership of this issue.
