### ISSUE TITLE
Kandy Login issue

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#33]
I am using the latest master branch of Kandy Phonegap repo (8040efc943357f6ba4554bb86d5bdde64311ef2a) which uses kandyIOS SDK 1.6 and building an iOS app

Here is what we are doing:

User logs into our app, upon successful login we are logging the user to kandy (we get the kandy creds from the back end)

I noticed after a successful login into Kandy If I don't logout explicitly (from Kandy), next time neither the success nor the error callback are fired?

    Kandy.access.login(
        function(){
            .....  // this is not fired
    },
    function(e){
           ...... // this is not fired either
    },
    username,
    password
    )

This is affecting Kandy logout too, so if the login is what I mentioned above the logout also seems to do nothing

Has anyone faced similar issues?

Just wanted to know, are Kandy.access methods like login, logout, push are "side effect free", that means whenever I call these methods with proper parameters it should either say it have done this action successfully or I have failed, The problem is I don't have a way to route my code if says neither

I remember last time when I tried it (around 4 months back), it was VERY consistent and was logging me into Kandy almost every time without any issues, so don't know what changed. I believe the internal REST API call should just validate the creds and return the access token whenever it is called, but that is  just my view.

The solution MIGHT be to ensure a logout happens after a login, push disable happens when enabling push next time.. but just wanted to be clear. I think once I login and don't logout, its gonna make me wait for some time before I can login again (just don't know what the time interval is, I think its more than 15 mins, probably).

**Comment by srbaskar** [comment]
Hi,

I’m invoking to Kandy.access.login method multiple times and getting the response every time.

Please share the steps to re-produce the error.

For previous versions (4 months back), Kandy Plugin would not allow the app run in background, i.e every time application will start from launching.

Thanks,
Srini
