### ISSUE TITLE
Kandy.onChatReceived not working on iOS9

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#34]
Kandy.onChatReceived is not firing in iOS9, it works fine in iOS 7x and 8x though

**Comment by srbaskar** [comment]
Hi,

I'm not able to re-produce this error on my device (iOS 9.1)

We'll have a screen-sharing session and fix the issue.

Thanks,
Srini

**Comment by primableatom** [comment]
This is works for now in iOS 9.1 . I was testing this in an iPad yesterday but today I have both the iPhones. I think it should work fine. Thanks. Closing this issue for now
