### ISSUE TITLE
Kandy.access.login triggers the success callback twice

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#38]
This is not a showstopper but I noticed the success callback for Kandy.access.login seems to get triggered twice

    Kandy.access.login(
        function(){
            alert('login success'); // this will be triggered twice   
        },
        function(e){
            alert('Login Error: ' + e); 
        },
        username,
        password
    )

**Comment by srbaskar** [comment]
Hi Anup,

Is it happens in a Test app?

I've tested in 'Test app' which you have created with latest changes and getting the 'login success' alert only once (i.e login callback triggered only once).

Please share the steps to re-produce this error.

Thanks,
Srini
