### ISSUE TITLE
Video dialog not showing in Android

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#42]
On making a Video Call via Kandy.call.createVoipCall, the Dialog is not shown in Android.

This is what I tried.
- Made a video call from Android to iOS, the ringtone got triggered but video dialog didn't show up in Android. The call was received by the iOS app without any issues.
- Made a video call from iOS to Android, the incoming ringtone got triggered but the call was never received in Android as the chooser never came up.

More details

Android 
Version - 5.1.1 (Lollipop)
Kandy SDK - 1.6.08

iOS
Version - 8.1.1
Kandy SDK - 1.6

**Comment by primableatom** [comment]
@Srini, Did you get a chance to look into this?

**Comment by kodeplusdev** [comment]
More context from our chat:

Just for the context copying the message from another group chat

Hey Guys, I found Android “KandyVideoView.java” isn’t handling call features at a native level like its iOS counterpart “CallViewController.m”. 

While I know its good to do that as for a phonegap app as we need to give the developers flexibility to design their own video player.. BUT until that is done fully I think we should add call handling capabilities back in Android (as it was 8 months ago).. The REAL flexibility I think would be expose the video stream / make the video appear by passing a DOM container, as without that the implementation would be half baked.. 

On Another note I tested the Demo App. And it doesn’t show the call dialog for an Android app while receiving the call from an iOS app.
So If we can just add the native call handling capabilities back to Android VideoView like it does today for iOS that will solve the problem for us.

--------------
I am sending along a sample app reproducing the Android call issue.. 

You can build two Android apps for user1 and user2.. by updating the loggedUser = user1 or user2 in index.js

As you can see.. The clicking on call seems trigger it and even rings for both caller and the callee.. but the dialog doesn’t pop up
Here is a dropbox link to the app https://www.dropbox.com/s/funv21wtmahkjs8/test.zip?dl=0

------------------------

**Comment by kodeplusdev** [comment]
I found that you create a call using a button and trigger `Kandy.call.createVoipCall` function. This will only create a call without dialog because you are using APIs plugin, not our widget `<kandy widget="call"></kandy>`.

If you want to show local/remote video view, you can call `showLocalVideo`/`hideLocalVideo`, `showRemoteVideo`/`hideRemoteVideo`.

**Comment by primableatom** [comment]
https://www.dropbox.com/s/f7jl427i27948le/kandy_issue.mp4?dl=0 

Here is a screencast of the plugins demo app showing Android issue while receiving a call.  

As you would notice

 - I triggered a call from the iOS app and it didn't trigger the Kandy widget dialog on the Android side.
 - I triggered a call from Android, it displayed the widget dialog BUT without controls like hang, mute.. and     DID trigger a call in the iOS side.
  - The same demo code triggered a NATIVE video dialog for iOS BUT Kandy widget dialog for Android which effectively means that the iOS native dialog and notifications hijack the widget dialog.

**Comment by kodeplusdev** [comment]
I'll add a native android dialog to solve this issue. And, can you send me android's logcat?

**Comment by kodeplusdev** [comment]
Can you install CPU-Z app and send me the result? Currently the Kandy Android only works on ARM architect, not intel.

**Comment by primableatom** [comment]
@Khoa, thanks.. that latest update fixed it,

While I am kinda able to use the call widget in our App I think it has one UI limitation which makes me think the native dialog will be good for us now

The method Kandy.call.showRemoteVideo doesn't let me have control over the video player DOM container, all I can do is adjust left,top width and height and they are not pixels either.

So, it limits the ability to accommodate different phones of different form factors.

**Comment by primableatom** [comment]
Hey Khoa, thanks for the update.. I am able to trigger a native call dialog from Android.. But upon receiving the in call dialog shows the placeholder image instead of the video although I can hear the Audio


![d3067144b6d9b1c2e5cd19195d2011e0a234b05bbb2d74c0b8pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/4652087/11950903/cbe4a2ba-a8b2-11e5-852e-2ab3ea07a572.jpg)
![screenshot_20151222-133624](https://cloud.githubusercontent.com/assets/4652087/11950910/e43a22a4-a8b2-11e5-8d29-4c9c4f7b7729.png)

**Comment by primableatom** [comment]
This is what I got from logcat on clicking on the video for the recieiver

E/KANDY_b (15185): videoStartFailed: callInterface: com.genband.mobile.impl.services.call.IncomingCall@3f06a927 error: [6][Video Start Local Offer Operation operation is not valid.]
E/KANDY_SPiDRSDK_Call(15185): unMute call can not be done. Error : current state is already unmute
E/KANDY_b (15185): unMuteCallFailed: callInterface: com.genband.mobile.impl.services.call.IncomingCall@3f06a927 error: [5][current state is already unmute]
