### ISSUE TITLE
Call example not working, demo app crashes on receiving calls

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#8]
The call example in the demo app doesn't seem to work. The callee's app crashes on receiving the call.
It happens for both video and no video calls. Also the push state was enabled for the both the users.

**Comment by kodeplusdev** [comment]
It's working on our end. Can you please provide more logs infor?

There is a pure Kandy Android app demo(no phonegap related). Can you also please try it out and see if it works? If something works on the app demo but not on the phonegap, then we would narrow down to the issue to phonegap. If something also doesn't work on the app demo, then we could narrow down the issue to Kandy or Android.

https://rink.hockeyapp.net/api/2/apps/9846845b4e90da8b044c60b17aa394d1/app_versions/25?format=apk&avtoken=e60376bcb614ea51eb49c842fe219e98b6abecb5

**Comment by primableatom** [comment]
I am still getting the this even if https://github.com/Kandy-IO/kandy-phonegap/issues/9 this is fixed. On receiving the call the app just crashes.

**Comment by primableatom** [comment]
Just tested the native demo app and the call is working. I think we may be safe to assume that there are some issues with phonegap demo app unless I am doing something wrong

**Comment by primableatom** [comment]
W/PackageManager( 1039): Unknown permission .permission.C2D_MESSAGE in package com.example.hello
I/ActivityManager( 1039): Force stopping com.example.hello appid=10102 user=-1: uninstall pkg
I/PackageManager( 1039): Package com.example.hello codePath changed from /data/app/com.example.hello-1.apk to /data/app/com.example.hello-2.apk; Retaining data and using new
I/ActivityManager( 1039): Force stopping com.example.hello appid=10102 user=-1: update pkg
W/PackageManager( 1039): Code path for pkg : com.example.hello changing from /data/app/com.example.hello-1.apk to /data/app/com.example.hello-2.apk
W/PackageManager( 1039): Resource path for pkg : com.example.hello changing from /data/app/com.example.hello-1.apk to /data/app/com.example.hello-2.apk
W/PackageManager( 1039): Unknown permission .permission.C2D_MESSAGE in package com.example.hello
I/ActivityManager( 1039): Force stopping com.example.hello appid=10102 user=0: pkg removed
D/BackupManagerService( 1039): Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.example.hello flg=0x4000010 (has extras) }
D/BackupManagerService( 1039): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.hello flg=0x4000010 (has extras) }
I/ActivityManager( 1039): START u0 {act=android.intent.action.MAIN flg=0x10000000 cmp=com.example.hello/.MainActivity} from pid 25526
I/ActivityManager( 1039): Start proc com.example.hello for activity com.example.hello/.MainActivity: pid=25540 uid=10102 gids={50102, 3003, 1028, 1015}
D/SFPerfTracer(  259):        layers: (6:11) (DimLayer: 0:149)* (FocusedStackFrame: 0:655)* (StatusBar: 5:10775) (NavigationBar: 5:8325) (com.android.systemui.ImageWallpaper: 0:259) (DimLayer: 0:81)* (DimLayer: 0:18)* (com.android.launcher/com.android.launcher2.Launcher: 0:102) (AtchDlg:com.android.launcher/com.android.launcher2.Launcher: 8:26) (Starting com.example.hello: 9:12) 
I/LaunchCheckinHandler( 1039): Displayed com.example.hello/.MainActivity,cp,ca,668
D/SFPerfTracer(  259):        layers: (3:12) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 1:10809) (NavigationBar: 0:8330) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.android.launcher/com.android.launcher2.Launcher: 0:102)* (AtchDlg:com.android.launcher/com.android.launcher2.Launcher: 0:31)* (Starting com.example.hello: 0:36)* (com.example.hello/com.example.hello.MainActivity: 0:46) 
D/SFPerfTracer(  259):        layers: (3:9) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 1:10901) (NavigationBar: 0:8330) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:55) 
D/SFPerfTracer(  259):        layers: (4:10) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 0:10978) (NavigationBar: 0:8331) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 17:79) (InputMethod: 14:18) 
D/SFPerfTracer(  259):        layers: (4:10) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 0:10984) (NavigationBar: 0:8331) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 2:96) (InputMethod: 3:109) 
D/SFPerfTracer(  259):        layers: (4:10) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 0:10986) (NavigationBar: 0:8331) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 2:136) (InputMethod: 5:182) 
D/SFPerfTracer(  259):        layers: (3:10) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 40:11029) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:168) (InputMethod: 0:224)* 
D/SFPerfTracer(  259):        layers: (3:9) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 46:11131) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 1:169) 
D/SFPerfTracer(  259):        layers: (6:14) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 0:11205) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:169) (: 0:5)* (: 1:19) (: 0:7)* (: 0:7) (: 0:15) 
D/SFPerfTracer(  259):        layers: (5:14) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 1:11274) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:169) (: 0:5)* (: 1:73) (: 0:12)* (: 0:9) (: 0:29)* 
D/SFPerfTracer(  259):        layers: (3:13) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 1:11367) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:169) (: 0:5)* (: 0:79)* (: 0:12)* (: 0:9)* 
D/SFPerfTracer(  259):        layers: (3:9) (DimLayer: 0:149)* (FocusedStackFrame: 0:659)* (StatusBar: 0:11405) (NavigationBar: 0:8332) (com.android.systemui.ImageWallpaper: 0:260)* (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 22:244) 
D/dalvikvm(25540): Trying to load lib /data/app-lib/com.example.hello-2/libjingle_peerconnection_so.so 0x4194a258
D/dalvikvm(25540): Added shared lib /data/app-lib/com.example.hello-2/libjingle_peerconnection_so.so 0x4194a258
D/dalvikvm(25540): Trying to load lib /data/app-lib/com.example.hello-2/libjingle_peerconnection_so.so 0x4194a258
D/dalvikvm(25540): Shared lib '/data/app-lib/com.example.hello-2/libjingle_peerconnection_so.so' already loaded in same CL 0x4194a258
E/AndroidRuntime(25540): Process: com.example.hello, PID: 25540
W/ActivityManager( 1039):   Force finishing activity com.example.hello/.MainActivity
W/ActivityManager( 1039): Activity pause timeout for ActivityRecord{4214ddd0 u0 com.example.hello/.MainActivity t35 f}
D/SFPerfTracer(  259):        layers: (6:11) (DimLayer: 0:164) (FocusedStackFrame: 0:662)* (StatusBar: 7:11453) (NavigationBar: 8:8351) (com.android.systemui.ImageWallpaper: 0:262) (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 12:296)* (Application Error: com.example.hello: 1:17) (com.android.launcher/com.android.launcher2.Launcher: 1:5) 
I/ActivityManager( 1039): Process com.example.hello (pid 25540) has died.
W/ActivityManager( 1039): Service ServiceRecord{426e6b38 u0 **com.example.hello/com.genband.mobile.impl.services.registration.GeneralRenewalAndroidService} in process ProcessRecord{42196b60 25540:com.example.hello/u0a102} not same as in map: null
W/ActivityManager( 1039): Service ServiceRecord{4233ffb0 u0 com.example.hello/com.genband.mobile.core.NotificationEngine.NotificationAndroidService} in process ProcessRecord{42196b60 25540:com.example.hello/u0a102} not same as in map: null**
I/WindowState( 1039): WIN DEATH: Window{4238d870 u0 com.example.hello/com.example.hello.MainActivity}
D/SFPerfTracer(  259):        layers: (4:11) (DimLayer: 0:176)* (FocusedStackFrame: 0:663)* (StatusBar: 25:11519) (NavigationBar: 0:8351) (com.android.systemui.ImageWallpaper: 0:262) (DimLayer: 0:81)* (DimLayer: 0:18)* (com.example.hello/com.example.hello.MainActivity: 0:296)* (Application Error: com.example.hello: 0:48)* (com.android.launcher/com.android.launcher2.Launcher: 0:6)

**Comment by primableatom** [comment]
Just wanted to know, did the above logs helped in finding the issue?

**Comment by kodeplusdev** [comment]
Fixed. Please verify. Thanks!

**Comment by primableatom** [comment]
It works.. Thanks!!
