### ISSUE TITLE
Kandy.call.createVoipCall method is firing error callback with "JSON error".

### ISSUE THREAD

**Issue by primableatom** [Kandy-IO/kandy-phonegap#9]
Kandy.access.login(
            function(){
                Kandy.push.enable(
                    function(){
                        //success
                        alert('push enabled');
                        Kandy.initialize();
                        Kandy.call.createVoipCall(
                            function(){
                                alert('call success');
                            },
                            function(e){
                                alert(e); // this gets fired with "JSON error"
                            },
                            'user1@anup.com',
                            true
                        );
                    },
                    function(e){
                        alert(e);
                    }
                );
                
            },
            function(e){
                alert(e);
            },
            'user2@anup.com',
            'password123'
        );

**Comment by kodeplusdev** [comment]
This is fixed. Please verify. Thanks!

**Comment by primableatom** [comment]
That fixed it... Thanks!
